### ISSUE TITLE
Lambda Context?

### ISSUE THREAD

**Issue by kalzoo** [lazear/axum-aws-lambda#10]
What do you think about carrying the [lambda_http::Context](https://docs.rs/lambda_http/latest/lambda_http/ext/extensions/trait.RequestExt.html#tymethod.lambda_context_ref) forward into the request? That data is necessary for auth claims when using Cognito, among other things.

I imagine we'd use [Extensions](https://docs.rs/http/latest/http/struct.Extensions.html) for that; I can take a shot at it if you're interested.

**Comment by lazear** [comment]
Makes sense to me - please open a PR! Extensions is what I typically use for passing along JWT/etc to route handlers - also can be nice to implement `FromRequestParts` so that it's more ergonomic to access (will require a new type though).

**Comment by kalzoo** [comment]
The best PR is no PR - no changes needed! I had misunderstood how that context was being handled; your `Service` already forwards it the existing `Extensions` and thus already has `FromRequestParts` support. That is, both of these "just work" ™️ :

```rust
async fn get_context(Extension(context): Extension<lambda_http::Context>) {
    // ...
}

async fn get_request_context(Extension(request_context): Extension<lambda_http::request::RequestContext>) {
   // ...
}
```

Thanks for a great crate!

🚀
